name: Process Feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Install Git
        run: sudo apt-get install git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Runner"
          git config user.email "ray@planetoftheweb.com"
      - name: execute script
        run: |
          python feed.py
      - name: Commit changes
        run: |
          git add -A
          git commit -m "Update files from feed.py"
      - name: Push changes
        run: git push
